/*
    This header file is generated by sotom at 2023-05-14 11:37:54.385337
    visit sotom at https://github.com/sislamrafi/sotom
*/

#ifndef __LIBS__ESC_H__
#define __LIBS__ESC_H__

//define all your function prototypes and variables under this line

#include "../../main/board.h"
#include "../../libs/gpio/gpio.h"
#include "../../libs/timer/timer.h"

typedef enum PWM_CHANNEL {
    CHANNEL1,
    CHANNEL2,
    CHANNEL3,
    CHANNEL4,
} PWM_CHANNEL;

typedef struct
{
    /* data */
    GPIO_t* gpio;
    uint8_t pin;
    PWM_CHANNEL channel;
} ESC;

void ESC_ConfigWithTimer2(void);
void ESC_Attach(ESC* esc);
void ESC_write(ESC* esc, uint16_t micros);

#endif
